# Generated by Django 4.1.7 on 2023-04-01 09:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator(message='Некорректный формат электронного адреса.')])),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'db_table': 'owner',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=10000, message='Артикул должен быть не меньше 10000.')], verbose_name='Артикул')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 2, 9, 22, 25, 444175, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 6, 30, 9, 22, 25, 444175, tzinfo=datetime.timezone.utc))], verbose_name='Конец')),
                ('date_start', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 2, 9, 22, 25, 444175, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 6, 30, 9, 22, 25, 444175, tzinfo=datetime.timezone.utc))], verbose_name='Начало')),
                ('payload', models.PositiveSmallIntegerField(verbose_name='Масса товара (т)')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазина',
                'db_table': 'product_shop_order',
                'ordering': ('date_start',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.PositiveSmallIntegerField(verbose_name='Масса поставки (т)')),
            ],
            options={
                'verbose_name': 'Товар в поставке',
                'verbose_name_plural': 'Товары в поставке',
                'db_table': 'product_transit',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.PositiveIntegerField(verbose_name='Масса товара (т)')),
            ],
            options={
                'verbose_name': 'Товар на складе',
                'verbose_name_plural': 'Товары на складе',
                'db_table': 'product_warehouse',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'db_table': 'shop',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 2, 9, 22, 25, 445172, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 6, 30, 9, 22, 25, 445172, tzinfo=datetime.timezone.utc))], verbose_name='Конец')),
                ('date_start', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 2, 9, 22, 25, 445172, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 6, 30, 9, 22, 25, 445172, tzinfo=datetime.timezone.utc))], verbose_name='Начало')),
            ],
            options={
                'verbose_name': 'Поставка на склад',
                'verbose_name_plural': 'Поставки на склад',
                'db_table': 'transit',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Марка машины')),
                ('max_capacity', models.PositiveSmallIntegerField(verbose_name='Вместимость машины (т)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'db_table': 'vehicle',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Поставка машиной',
                'verbose_name_plural': 'Поставки машиной',
                'db_table': 'vehicle_transit',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес склада')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Вместимость склада')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название склада')),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
    ]
