# Generated by Django 4.1.7 on 2023-04-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
    ]
