# Generated by Django 4.1.7 on 2023-04-04 12:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='Осуществлено')),
                ('date_start', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 5, 12, 53, 5, 258992, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 7, 3, 12, 53, 5, 258992, tzinfo=datetime.timezone.utc))], verbose_name='Начало')),
                ('date_end', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 4, 5, 12, 53, 5, 258992, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 7, 3, 12, 53, 5, 258992, tzinfo=datetime.timezone.utc))], verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазина',
                'db_table': 'order_table',
                'ordering': ('date_start',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Масса товара (т)')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'db_table': 'product_order',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductShopOrder',
        ),
    ]
