# Generated by Django 4.1.7 on 2023-04-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleorder',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Машина в заказке', 'verbose_name_plural': 'Машины в заказе'},
        ),
        migrations.AlterModelOptions(
            name='vehicletransit',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Машина в поставке', 'verbose_name_plural': 'Машины в поставке'},
        ),
    ]
