# Generated by Django 4.1.7 on 2023-04-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_vehicleorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
